apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        hosts {
           192.168.1.6 keycloak.docker.internal grafana.docker.internal alertmanager.docker.internal prometheus.docker.internal
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-16T12:50:14Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "248"
  uid: 41cee254-909b-43c7-878a-f429345b295c
