apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
   app: keycloak
spec:
  instances: 1
  hostname:
    hostname: keycloak.docker.internal